name: Create Android Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0-beta)'
        required: true
        type: string

jobs:
  build:
    name: Build Android Package
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 25

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: nebula/go.sum

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Get build name and number
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          flutter pub get
          touch env.sh
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BUILD_NAME="${{ inputs.version }}"
          else
            BUILD_NAME="${GITHUB_REF#refs/tags/v}"
            BUILD_NAME="${BUILD_NAME%-*}"
          fi
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=1" >> $GITHUB_ENV

      - name: Build Android
        run: |
          flutter build apk --build-number="$BUILD_NUMBER" --build-name="$BUILD_NAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ env.BUILD_NAME }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.BUILD_NAME }}
          files: |
            build/app/outputs/apk/release/app-release.apk 
